### ISSUE TITLE
Request for Local Development Documentation and Environment File Example

### ISSUE THREAD

**Issue by JamiltonQuintero** [Justedlev/justedlevhub-api-gateway#3]
Dear Justredlev Team,

I hope this message finds you well. My name is Jamilton Quintero, and I am reaching out to inquire about the possibility of enhancing the project documentation to facilitate local development setup for contributors.

While exploring your project, I noticed that specific details on setting up a local development environment might be further elaborated. As a prospective contributor, I believe that a comprehensive README file, including step-by-step instructions for local setup, would be incredibly beneficial. Moreover, the inclusion of an example environment (.env.example) file could significantly streamline the setup process by providing clear guidance on the necessary environment variables.

I understand that maintaining and improving documentation requires valuable time and resources. However, I am confident that such additions would not only aid current and future contributors but also foster a more welcoming and accessible development community.

If this suggestion aligns with your vision for the project, I would be more than happy to discuss it further or assist in any way possible. I also welcome any guidelines or requirements you might have for contributing to the documentation.

Thank you for considering my request. I greatly appreciate the hard work and dedication you've put into this project, and I am eager to contribute to its continued success.

Warm regards.

**Comment by justedlev** [comment]
@JamiltonQuintero Hello 👋, sorry for the delay

First I'll add the detail documentation about the configuration and usage, thanks🙌.
Second this repo for my inner projects usage.
Third I'll separate the impl to many small projects because in this I also use the kaycloack integration 🤔.

**Comment by justedlev** [comment]
Hi @JamiltonQuintero I implemented some solution for the api gateway if you still interested https://github.com/Justedlev/bridgewayhub?tab=readme-ov-file#bridgeway-hub
